stages:
  - deploy

build:
  stage: deploy
  before_script:
    - echo "build begin!"
    - mvn clean
    - mvn install
  script:
    - mvn package
    - echo "build success!"
  after_script:
    - echo "deploy begin!"
#    - /usr/local/tomcat/bin/shutdown.sh
    - rm -rf /usr/local/tomcat/webapps/orange*
    - cp target/orange.war /usr/local/tomcat/webapps/
#    - /usr/local/tomcat/bin/startup.sh
    - echo "deploy success!"
  tags:
    - my-tag

