spring:

  datasource:
    url: jdbc:mysql://localhost:3306/orange?useUnicode=true&characterEncoding=utf-8
    username: root
    password: song.1005
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.qq.com
    username: 293410177@qq.com
    password: knjuvijxvqafcaei
    default-encoding: UTF-8
    test-connection: true

  jpa:
    show : ture
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hbm2ddl:
        auto: update

  application:
    name: orange

  rabbitmq:
    host: 118.24.216.163
    port: 5672
    username: admin
    password: Swing.1993


mail.fromMail.addr: 293410177@qq.com

