spring:

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orange?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: song.1005

  jpa:
    show: ture
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hbm2ddl:
        auto: update

  application:
    name: orange

mybatis:
  type-aliases-package: com.swing.orange.entity

mapper:
  not-empty: false
  mappers:
    - tk.mybatis.springboot.util.MyMapper
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true

info:
  app:
    name: orange
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /swing
