spring:

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/orange?useUnicode=true&characterEncoding=utf-8
    username: root
    password: song.1005
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.qq.com
    username: superme@swing1993.cn
    password: knjuvijxvqafcaei
    default-encoding: UTF-8
    test-connection: true

  jpa:
    show : ture
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hbm2ddl:
        auto: update

  application:
    name: orange

  rabbitmq:
    host: 118.24.216.163
    port: 5672
    username: admin
    password: Swing.1993


mail.fromMail.addr: superme@swing1993.cn

#gitlab_rails['smtp_enable'] = true
#gitlab_rails['smtp_address'] = "smtp.qq.com"
#gitlab_rails['smtp_port'] = 465
#gitlab_rails['smtp_user_name'] = "superme@swing1993.cn"
#gitlab_rails['smtp_password'] = "knjuvijxvqafcaei"
#gitlab_rails['smtp_authentication'] = "login"
#gitlab_rails['smtp_enable_starttls_auto'] = true
#gitlab_rails['smtp_tls'] = true
#gitlab_rails['smtp_domain'] = "qq.com"
#gitlab_rails['gitlab_email_from'] = "superme@swing1993.cn"

