spring:

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orange?useUnicode=true&characterEncoding=utf-8
    username: root
    password: song.1005

  mail:
    host: smtp.qq.com
    username: superme@swing1993.cn
    password: knjuvijxvqafcaei
    default-encoding: UTF-8
    test-connection: false

  jpa:
    show : ture
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hbm2ddl:
        auto: update

  application:
    name: orange

mybatis:
  type-aliases-package: com.swing.orange.entity

mail.fromMail.addr: superme@swing1993.cn

